env:
  browser: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:react/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  react:
    version: 16.13.1
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  eol-last: 2
  no-console: warn
  react/react-in-jsx-scope: 0 # disable this rule when using next.js
  react/prop-types: 0